/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon;

import java.awt.Color;
import java.io.InputStream;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 * 
 * @Bruno C. Manso
 */
public class PokemonGame extends javax.swing.JFrame {

    public Pokemon pikachu1;
    public Pokemon raichu1;
    public Pokemon ponyta1;
    public Pokemon rapidash1;
    
    /**
     * Creates new form PokemonGame
     */
    public PokemonGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RaichuVida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PikachuVida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RapidashVida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PonytaVida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();
        cenario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/raichu.png"))); // NOI18N

        RaichuVida.setBackground(new java.awt.Color(0, 0, 0));
        RaichuVida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RaichuVida.setForeground(new java.awt.Color(0, 51, 204));
        RaichuVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RaichuVida.setText("200");
        RaichuVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaichuVidaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/pikachu.png"))); // NOI18N

        PikachuVida.setBackground(new java.awt.Color(0, 0, 0));
        PikachuVida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PikachuVida.setForeground(new java.awt.Color(0, 51, 204));
        PikachuVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PikachuVida.setText("160");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/rapidash.png"))); // NOI18N

        RapidashVida.setBackground(new java.awt.Color(0, 0, 0));
        RapidashVida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RapidashVida.setForeground(new java.awt.Color(0, 51, 204));
        RapidashVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RapidashVida.setText("250");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/ponyta.png"))); // NOI18N

        PonytaVida.setBackground(new java.awt.Color(0, 0, 0));
        PonytaVida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PonytaVida.setForeground(new java.awt.Color(0, 0, 204));
        PonytaVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PonytaVida.setText("150");

        jButton1.setText("INICIAR BATALHA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtSair.setText("SAIR");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RaichuVida, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RapidashVida)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PikachuVida, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PonytaVida))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(BtSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PikachuVida)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RaichuVida))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RapidashVida)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PonytaVida))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(BtSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/cenario0.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images/titulo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cenario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel2)
                .addGap(0, 193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cenario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void animacao()
    {
        pikachu1 = new Pikachu("Pikachu");
        raichu1 = new Raichu ("Raichu");
        ponyta1 = new Ponyta("Ponyta");
        rapidash1 = new Rapidash("Rapidash");
        new Thread(new Runnable()
        {
            Random semente = new Random();
            int p1;
            int p2;
            @Override 
            public void run()
            {
               while (true)
               {
                   p1=semente.nextInt(2)+1;
                   if (p1==1) //pikachu ataca
                   {
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario0.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario1.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       ponyta1.setPontosVida(ponyta1.getPontosVida()-pikachu1.getDano());
                       PonytaVida.setText(Integer.toString(ponyta1.getPontosVida()));
                       if (ponyta1.getPontosVida()<=50)
                           PonytaVida.setForeground(Color.red);
                       else if (ponyta1.getPontosVida()<=100)
                           PonytaVida.setForeground(Color.yellow);
                   }
                   else if (p1==2) //raichu ataca
                   {
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario0.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario2.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       rapidash1.setPontosVida(rapidash1.getPontosVida()-raichu1.getDano());
                       RapidashVida.setText(Integer.toString(rapidash1.getPontosVida()));
                       if (rapidash1.getPontosVida()<=50)
                           RapidashVida.setForeground(Color.red);
                       else if (rapidash1.getPontosVida()<=100)
                           RapidashVida.setForeground(Color.yellow);
                   }  
                   if ((ponyta1.getPontosVida()<=0)||(rapidash1.getPontosVida()<=0))
                   {
                       JOptionPane.showMessageDialog(null, "WINNERS: PIKACHU E RAICHU!");
                       System.exit(0);
                   }
                   
                  p2=semente.nextInt(2)+3;
                   if (p2==3) //ponyta ataca
                   {
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario0.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario3.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       pikachu1.setPontosVida(pikachu1.getPontosVida()-ponyta1.getDano());
                       PikachuVida.setText(Integer.toString(pikachu1.getPontosVida()));
                       if (pikachu1.getPontosVida()<=50)
                           PikachuVida.setForeground(Color.red);
                       else if (pikachu1.getPontosVida()<=100)
                           PikachuVida.setForeground(Color.yellow);
                   } 
                   else if (p2==4) //rapidash ataca
                   {
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario0.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("./images/cenario4.png")));
                       try {
                           Thread.currentThread().sleep(1000);
                       } catch (InterruptedException ex) {
                           System.err.println("Erro.");
                       }
                       raichu1.setPontosVida(raichu1.getPontosVida()-rapidash1.getDano());
                       RaichuVida.setText(Integer.toString(raichu1.getPontosVida()));
                       if (raichu1.getPontosVida()<=50)
                           RaichuVida.setForeground(Color.red);
                       else if (raichu1.getPontosVida()<=100)
                           RaichuVida.setForeground(Color.yellow);
                   } 
                   if ((pikachu1.getPontosVida()<=0)||(raichu1.getPontosVida()<=0))
                   {
                       JOptionPane.showMessageDialog(null, "WINNERS: PONYTA E RAPIDASH!");
                       System.exit(0);
                   }
               }
            }
        
        }).start();
                
    }
    
    public void som()
    {
        try
        {
          String rec = "./sound/battle.wav";
          InputStream input = getClass().getResourceAsStream(rec);
          Clip clip = AudioSystem.getClip();
          AudioInputStream audioInput = AudioSystem.getAudioInputStream(input);
          clip.open(audioInput);
          clip.loop(0);
        }catch (Exception e)
        {
            System.err.println("Erro de som!");
        }
    }
    
    
    private void RaichuVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaichuVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RaichuVidaActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        RapidashVida.setEditable(false);
        PonytaVida.setEditable(false);
        PikachuVida.setEditable(false);
        RaichuVida.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        som();
        jButton1.setEnabled(false);
        animacao();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSair;
    private javax.swing.JTextField PikachuVida;
    private javax.swing.JTextField PonytaVida;
    private javax.swing.JTextField RaichuVida;
    private javax.swing.JTextField RapidashVida;
    private javax.swing.JLabel cenario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
